## Docker Container 
@url = http://localhost:8083

## Local Developer machine
# @url = http://localhost:7000

###
# @name submitForReview
POST {{url}}/submit
Content-Type: application/json

{
  "id": "1",
  "author": "Sienfeld",
  "url":"http://articles/showaboutnothing"
}

###
POST {{url}}/submit
Content-Type: application/json

{
  "author": "Kramer",
  "url":"http://articles/kosmo"
}

###
# @name getAllAssignedTasks
GET {{url}}/tasks?assignee=editors

###

POST {{url}}/review
Content-Type: application/json

{
  "id": "{{getAllAssignedTasks.response.body.$[0].id}}",
  "status": true
}

###
GET {{url}}/actuator/flowable

###
GET {{url}}/history

###
GET {{url}}/history/servicetasks

### Kafka API
# groupid = test

# ppcm-po-kafka-dev
# api/addDatatotopic
# topic
# request
# "incomingMessageEvent":{  "id": "1",  "author": "Sienfeld",  "url":"http://articles/showaboutnothing"}
